# Generated by Django 5.2.5 on 2025-10-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_time_for_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
