# Generated by Django 5.2.5 on 2025-10-09 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0003_initial'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
