# Generated by Django 5.2.5 on 2025-10-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('pending_approval', 'Pending Approval'), ('returned', 'Returned for Rework'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
