# Generated by Django 5.2.5 on 2025-10-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='normal_status',
            field=models.CharField(choices=[('todo', 'To Do'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('pending_approval', 'Pending Approval'), ('returned', 'Returned for Rework'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='in_progress', max_length=20),
        ),
    ]
