# Generated by Django 5.2.5 on 2025-10-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_normal_status_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='normal_status',
            field=models.CharField(choices=[('no_done', 'No Done'), ('done', 'Done')], default='no_done', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('pending_approval', 'Pending Approval'), ('returned', 'Returned for Rework'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='todo', max_length=20),
        ),
    ]
